### PR TITLE
Colour Range

### PR DESCRIPTION
**Pull request by bridges-wood**
Create a custom colour range for the randomly generated colours.

### CODE REVIEW

**Review by Drayz64 — CHANGES_REQUESTED** [review]
If the user creates a new module it only displays in the Chart Controls page when the user closes and runs the program again

Also I don't think the range of colours is working great:

image

**Review by Drayz64 — COMMENTED** [review]
I still wouldn't say that we are getting a range of colours, because you are using `float generated = rand.nextFloat();` it doesn't seem any different to just using completely random colours.

image

When I think about a range, the colours would be evenly spaced from from 0 to 300ish (or from red right round to magenta) and to do that you need to know the total number of modules and so to create this range every module's default colour would need to be created using state once all modules have been created.

This would also mean when a new module is created the default colours of all existing modules would have to be changed to keep the even spacing between modules

So maybe we are just better off going for the completely random colour option

**Comment by bridges-wood** [comment]
> I still wouldn't say that we are getting a range of colours, because you are using `float generated = rand.nextFloat();` it doesn't seem any different to just using completely random colours.
> 
> image
> 
> When I think about a range, the colours would be evenly spaced from from 0 to 300ish (or from red right round to magenta) and to do that you need to know the total number of modules and so to create this range every module's default colour would need to be created using state once all modules have been created.
> 
> This would also mean when a new module is created the default colours of all existing modules would have to be changed to keep the even spacing between modules
> 
> So maybe we are just better off going for the completely random colour option

Yeah, I can get what you mean, but the random option is probably best right now.

**Comment by Drayz64** [comment]
> Yeah, I can get what you mean, but the random option is probably best right now.

So are you sticking with the current random solution? Or are you going to re-implement the old random code:

```java
Random rand = new Random(hash(name));
float r = rand.nextFloat();
float g = rand.nextFloat();
float b = rand.nextFloat();
return new Color(r, g, b);
```

**Comment by bridges-wood** [comment]
> > Yeah, I can get what you mean, but the random option is probably best right now.
> 
> So are you sticking with the current random solution? Or are you going to re-implement the old random code:
> 
> ```java
> Random rand = new Random(hash(name));
> float r = rand.nextFloat();
> float g = rand.nextFloat();
> float b = rand.nextFloat();
> return new Color(r, g, b);
> ```

Just keep the current implementation.

**Review by Drayz64 — APPROVED** [review]
I guess this branch can finally be approved

**Pull request merged**
